apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
spec:
  selector:
    matchLabels:
      app: simple-flask-app
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
      - name: simple-flask-app
        image: facul/simple_flask_app
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
---
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: simple-flask-app
  ports:
    - port: 3000
      targetPort: 3000